apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: proxy-ingress
  namespace: K8S_APP_NAMESPACE_TO_REPLACE
  annotations:
    # alb.ingress.kubernetes.io/security-groups: DOS_API_SG_TO_REPLACE
