resources:
  - namespace.yaml
  - uec-dos-cs-api-deployment.yaml
  - uec-dos-cs-api-service.yaml
  - network-policy/uec-dos-cs-api-default-deny-ingress.yaml
  - network-policy/uec-dos-cs-api-allow-external-ingress.yaml

configMapGenerator:
  - name: uec-dos-cs-api-configmap
    literals:
      - PROFILE=PROFILE_TO_REPLACE

images:
  - name: 461183108257.dkr.ecr.eu-west-2.amazonaws.com/uec/uec-dos-cs-api/api
    newTag: UEC_DOS_CS_API_IMAGE_TAG_TO_REPLACE
