apiVersion: v1
kind: Service
metadata:
  name: uec-dos-api-cs
  namespace: K8S_APP_NAMESPACE_TO_REPLACE
  labels:
    app: uec-dos-api-cs
spec:
  type: ClusterIP
  selector:
    app: uec-dos-api-cs
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8443
