# Generated by Django 3.0.2 on 2020-02-19 12:03

import api.capacityauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DosUserAPIKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('dos_user_id', models.IntegerField()),
                ('dos_username', models.CharField(max_length=255, unique=True, validators=[api.capacityauth.models.DosUserAPIKey.validate_dos_username_exists])),
            ],
            options={
                'verbose_name': 'Capacity API Key for a DoS user',
                'verbose_name_plural': 'Capacity API keys for a DoS users',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
