# Generated by Django 3.0.2 on 2020-02-13 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacityauth', '0002_dosuserapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosuserapikey',
            name='dosusername',
            field=models.CharField(default='legacy', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
