# Generated by Django 3.0.2 on 2020-03-17 01:54

import api.capacityauth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capacityauth', '0003_create_cobbler_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityAuthDosUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dos_user_id', models.IntegerField()),
                ('dos_username', models.CharField(max_length=255, unique=True, validators=[api.capacityauth.models.CapacityAuthDosUser.validate_dos_username_exists])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
