# Generated by Django 3.0.2 on 2020-03-19 23:46

import api.authentication.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("authentication", "0001_create_admin_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="CapacityAuthDosUser",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                ("dos_user_id", models.IntegerField()),
                (
                    "dos_username",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[api.authentication.models.validate_dos_username_exists],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,),
                ),
            ],
            options={"verbose_name": "Capacity Auth DoS User", "verbose_name_plural": "Capacity Auth DoS Users",},
        ),
    ]
